name: create_pr
description: Create A Pull Request That will Trigger Workflows
inputs:
  base:
    description: The Base Ref to apply the diff
    required: false
  body:
    description: Optional body of the PR
    required: false
  commit-message:
    description: Commit Message for the PR
    required: true
  branch:
    description: The Branch to create for the PR
    required: true
  title:
    description: PR title - defaults to commit-message
    required: false
  app_id:
    description: Application ID used to make the PR
    required: true
  app_private_key:
    description: Application Private Key used to sign the PR
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check for changes
      id: is-dirty
      uses: streetsidesoftware/actions/public/dirty@v1

    - name: PR Body
      id: body
      uses: streetsidesoftware/actions/public/pr-body@v1
      with:
        title: ${{ inputs.title || inputs.commit-message }}
        message: ${{ inputs.body || '' }}

    - name: PR
      uses: streetsidesoftware/actions/.github/actions/pr@v1
      with:
        commit-message: ${{ inputs.commit-message }}
        title: ${{ steps.body.outputs.title }}
        branch: ${{ inputs.branch }}
        base: ${{ inputs.base || 'main' }}
        body: ${{ steps.body.outputs.body }}
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}
